#!/usr/bin/fish
while true
    set selection (ls -ahv --color=auto --group-directories-first | fzf \
        --bind="left:pos(2)+accept" \
        --bind="right:accept" \
        --bind="shift-up:preview-up" \
        --bind="shift-down:preview-down" \
        --bind="space:toggle" \
        --height=100% \
        --reverse \
        --multi \
        --info=default\
        --prompt="❱ " \
        --pointer=󰄾 \
        --marker=● \
        --border=bold \
        --border-label=$(pwd) \
        --preview-window=right:wrap:60% \
        --preview='~/.dotfiles/scripts/fzf_preview {}')
    if test -d "$selection"
        cd "$selection"
    else if test -f "$selection"
        set file_type (if string match -qr '\.lua|\.json' "$selection"; echo "text"; else; file -b --mime-type "$selection" | cut -d'/' -f1; end)
        switch $file_type
            case text
                nvim "$selection"
            case inode
                nvim "$selection"
            case '*'
                xdg-open "$selection" >/dev/null 2>&1
        end
    else
        break
    end
end
