#!/usr/bin/fish

tmux display-popup -E -w 60% -h 60% -x C -y C -T '[   App Launcher ]' 'fish -c "complete -C \'\'" | perl -wlane "print \$F[0] if defined \$F[1] && \$F[1] =~ /command/" | fzf --no-multi --height=100% >/tmp/tmux_fzf_synchronise_launchcmd'
echo (cat /tmp/tmux_fzf_synchronise_launchcmd)" >/dev/null 2>&1" | fish
