#!/usr/bin/fish

set PATH_SCRIPT "~/.dotfiles/scripts"

tmux display-popup -E -w 60% -h 60% -x C -y C -T '[  Menu ]' "fish -c \"echo '[1]    App Launcher
[2]    Extract Data
[3]    Fuzzy Find File
[4]    File Manager
[5]    Alsamixer Control Audio
[6]    Backlight Control
[7]    Bluetooth TUI
[8]    Btop
[9]    Lazygit
[10]   Network Manager
[11]   ProtonVPN Connect
[12]   ProtonVPN Fast Connect
[13]   ProtonVPN Disconnect
[14]   Warp Connect
[15]   Warp Disconnect
[16]   Tmux Plugin Manager Install
[17]   Tmux Plugin Manager Uninstall
[18]   Tmux Plugin Manager Update
[19]   Session Save
[20]   Session Restore
[21] 󰒲  Sleep' | fzf --height=100% --no-multi | string split -f1 ' ' -m1 | string replace -ar '[^0-9]' '' >/tmp/tmux_fzf_synchronise_index\""

set fzf_commands \
    "tmux run-shell -b \"$PATH_SCRIPT/fzf_applauncher\"" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/extrakto/scripts/open.sh '#{pane_id}'\"" \
    "tmux display-popup -E -w 60%  -h 60% -x C -y C -T '[   Fuzzy Find File ]' -d '#{pane_current_path}' '$PATH_SCRIPT/fzf_findFile'" \
    "tmux new-window -a -n '  [#I]' -c '#{pane_current_path}' '$PATH_SCRIPT/fileExplorer'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -T '[ Alsamixer ]' 'alsamixer'" \
    "tmux display-popup -E -w 60%  -h 60% -x C -y C -T '[ Backlight ]' '$PATH_SCRIPT/setBacklight set'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -T '[ Bluetooth ]' 'bluetui'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -T '[ Btop ]' 'sudo btop'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -T '[ Lazygit ]' -d '#{pane_current_path}' 'lazygit'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -B 'nmtui'" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -B 'protonvpn-cli connect'" \
    "tmux display-popup    -w 60%  -h 60% -x C -y C -T '[   ProtonVPNConnect ]' 'protonvpn-cli connect -fp tcp'" \
    "tmux display-popup    -w 60%  -h 60% -x C -y C -T '[   ProtonVPNDisconnect ]' 'protonvpn-cli disconnect'" \
    "tmux display-popup    -w 60%  -h 60% -x C -y C -T '[   Warp Connect ]' 'warp-cli connect'" \
    "tmux display-popup    -w 60%  -h 60% -x C -y C -T '[   Warp Disconnect ]' 'warp-cli disconnect'" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/tpm/bindings/install_plugins\"" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/tpm/bindings/clean_plugins\"" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/tpm/bindings/update_plugins\"" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/tmux-resurrect/scripts/save.sh\"" \
    "tmux run-shell -b \"/home/$USER/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh\"" \
    "tmux display-popup -E -w 100% -h 99% -x R -y S -B \"arttime --nolearn --hours 24 --theme dark --style 1 --pa '○' --pb '●' -t '❝Awesome Terminal❞' --pl 10 --ac 4 --tc 4 -a colorowl -b colorowl2\""
echo $fzf_commands[(cat /tmp/tmux_fzf_synchronise_index)]" >/dev/null 2>&1" | fish
